[package]
name = "yaserde"
version = "0.1.0"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]

[dependencies]
yaserde_derive = { path = "../yaserde_derive", optional = true }
regex = "0.2"
xml-rs = "0.7.0"

[dev-dependencies]
yaserde_derive = { path = "../yaserde_derive" }
