[package]
name = "yaserde-examples"
version = "0.0.1"
authors = ["Marc-Antoine Arnaud <maarnaud@media-io.com>"]
license = "MIT"
edition = "2018"

[dependencies]
yaserde = {version = "0.5.1", path = "../yaserde" }
yaserde_derive = {version = "0.5.1", path = "../yaserde_derive" }
xml-rs = "0.8.0"
log = "0.4"
simple_logger = "1.0"
